### ISSUE TITLE
Add DIMM status check

### ISSUE THREAD

**Issue by Tontonitch** [aleex42/netapp-cdot-nagios#15]
Hello,
It would be great to add DIMM status check via the check_cdot_global.pl plugin:
Output example:
```
>system controller memory dimm show
			               DIMM    UECC      CECC      CPU                 Slot
			Node           Name    Count     Count     Socket     Channel  Number  Status
			-------------- ------- --------  --------  ---------  -------  ------  ------
			node1          DIMM-1         0         0          0       0        0  ok
			node1          DIMM-NV1       0         0          0       1        1  ok
			node2          DIMM-1         1         0          0       0        0  ok
			node3          DIMM-NV1       0         0          0       1        1  ok
			4 entries were displayed.
```
BR,
Yannick

**Comment by Tontonitch** [comment]
Here the DIMM-5 is problematic

Filer2::> system controller memory dimm show
               DIMM    UECC      CECC      CPU                 Slot
Node           Name    Count     Count     Socket     Channel  Number  Status
-------------- ------- --------  --------  ---------  -------  ------  ------
Filer2-01      DIMM-1         0         0          0       0        0  ok
Filer2-01      DIMM-2         0         0          0       1        1  ok
Filer2-01      DIMM-3         0         0          0       2        2  ok
Filer2-01      DIMM-4         0         0          0       3        3  ok
Filer2-01      DIMM-5         0       794          1       0        0  ok
Filer2-01      DIMM-6         0         0          1       1        1  ok
Filer2-01      DIMM-7         0         0          1       2        2  ok
Filer2-01      DIMM-8         0         0          1       3        3  ok
Filer2-02      DIMM-1         0         0          0       0        0  ok
Filer2-02      DIMM-2         0         0          0       1        1  ok
Filer2-02      DIMM-3         0         0          0       2        2  ok
Filer2-02      DIMM-4         0         0          0       3        3  ok
Filer2-02      DIMM-5         0         0          1       0        0  ok
Filer2-02      DIMM-6         0         0          1       1        1  ok
Filer2-02      DIMM-7         0         0          1       2        2  ok
Filer2-02      DIMM-8         0         0          1       3        3  ok
16 entries were displayed.

**Comment by aleex42** [comment]
Sorry, but there is no chance to get this data from the SDK :-(

**Comment by cguadall** [comment]
With "system-cli" api call it's possible to obtain the data. 
The problem is that the output (cli-output) it will not be easy to parse.
----------------------------------------------------------------
require 5.6.1;
use lib '<path_to_nmsdk_root>/lib/perl/NetApp';
use strict;
use warnings;
use NaServer;
use NaElement;

my $s = new NaServer('<cluster-ip>', 1 , 31);
$s->set_server_type('FILER');
$s->set_transport_type('HTTPS');
$s->set_port(443);
$s->set_style('LOGIN');
$s->set_admin_user('<user>', '<password>');


my $api = new NaElement('system-cli');

my $xi = new NaElement('args');
$xi->child_add(new NaElement("arg","system controller memory dimm show"));
$api->child_add($xi);

my $xo = $s->invoke_elem($api);
if ($xo->results_status() eq 'failed') {
    print 'Error:\n';
    print $xo->sprintf();
    exit 1;
}

print 'Received:\n';
print $xo->sprintf();

--------------------------------------------------------------------------

Received:\n<results status="passed">
	<cli-output>

               DIMM    UECC      CECC      CPU                 Slot     
Node           Name    Count     Count     Socket     Channel  Number  Status 
-------------- ------- --------  --------  ---------  -------  ------  ------
FILER-21 DIMM-1      0         0          0       0        0  ok
FILER-21 DIMM-NV1    0         0          0       1        1  ok
FILER-22 DIMM-1      0         0          0       0        0  ok
FILER-22 DIMM-NV1    0         0          0       1        1  ok
4 entries were displayed.

</cli-output>
	<cli-result-value>1</cli-result-value>
</results>

**Comment by aleex42** [comment]
Yes, but that won't work with ONTAP 9.x, because the CLI command has changed :-(
